# This file specifies your Python application's runtime configuration
# including URL routing, versions, static file uploads, etc. See
# https://developers.google.com/appengine/docs/python/config/appconfig
# for details.

application: unikbscout
version: 0-2-0
runtime: python27
api_version: 1
threadsafe: yes

# Handlers define how to route requests to your application.
# This handler tells app engine how to route requests to a WSGI application.
# The script value is in the format <path.to.module>.<wsgi_application>
# where <wsgi_application> is a WSGI application object.
# This regex directs all routes to main.app
handlers:
- url: .*
  script: main.app
